# Generated by Django 4.2.1 on 2023-08-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_lesson_alter_profile_user_grade_profile_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='days',
            field=models.CharField(choices=[('Monday, Wednesday, Friday', 'Monday, Wednesday, Friday'), ('Tuesday, Wednesday, Friday', 'Tuesday, Wednesday, Friday')], max_length=100),
        ),
    ]
