# Generated by Django 4.2.1 on 2023-08-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_alter_lesson_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.profile'),
        ),
    ]
