# Generated by Django 4.2.1 on 2023-08-01 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_remove_profile_lesson_lesson_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='profil',
        ),
        migrations.AddField(
            model_name='profile',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_info', to='asosiy.lesson'),
        ),
    ]
