# Generated by Django 4.2.1 on 2023-08-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_remove_lesson_profil_profile_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lesson',
        ),
        migrations.AddField(
            model_name='profile',
            name='lesson',
            field=models.ManyToManyField(null=True, related_name='lesson_info', to='asosiy.lesson'),
        ),
    ]
