# Generated by Django 4.2.1 on 2023-08-01 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0008_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprofile',
            name='klass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_info', to='asosiy.class'),
        ),
    ]
