# Generated by Django 4.2.1 on 2023-08-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0010_grade_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_tolov', to='asosiy.lesson')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.profile')),
            ],
        ),
    ]
