# Generated by Django 4.2.1 on 2023-08-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0012_lessonprofile_tolov'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolov',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
